inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'bin/**'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/**/*'
    - 'spec/*'
    - 'app/helpers/sessions_helper.rb'
    - 'app/models/favorite.rb'
    - 'app/models/favorite.rb'
    - 'app/models/notification.rb'
    - 'app/models/user.rb'


  
Style/TrailingCommaInHashLiteral:
  Enabled: false
  
Style/BlockDelimiters:
  Enabled: false
  
Layout/FirstHashElementLineBreak:
  Enabled: false
  
Airbnb/OptArgParameters:
  Enabled: false
  
Style/ColonMethodCall:
  Enabled: false
  
Layout/IndentationConsistency:
  Enabled: false
  
Layout/IndentationWidth:
  Enabled: false
  
Style/MixinUsage:
  Enabled: false
  
Style/MutableConstant:
  Enabled: false
