version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Dockerコンテナのビルド
          command: docker-compose build
      - run:
          name: Dockerコンテナの起動
          command: docker-compose up -d
      - run:
          name: データベースのセットアップ
          command: docker-compose exec web rails db:create -d  &&  docker-compose exec web rails db:migrate


      - run:
          name: RSpecテスト実行
          command: docker-compose exec web bundle exec bin/rspec
      - run:
          name: Rubocopテスト実行
          command: docker-compose exec web bundle exec rubocop
      - run:
          name: Dockerコンテナの停止
          command: docker-compose down


