version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Dockerコンテナのビルド
          command: docker-compose build
      - run:
          name: Dockerコンテナの起動
          command: docker-compose up -d
      - run:
          name: データベースのセットアップ
          command: docker-compose exec web bundle exec rails db:create db:migrate RAILS_ENV=test


      - run:
          name: RSpecテスト実行
          command: docker-compose exec web bundle exec bin/rspec
      - run:
          name: Rubocopテスト実行
          command: docker-compose exec web bundle exec rubocop
      - run:
          name: Dockerコンテナの停止
          command: docker-compose down
    
deploy:
  machine:
      mage: circleci/classic:edge
  steps:
      - checkout
        # CircleCI に登録した秘密鍵を呼び出す
      - add_ssh_keys:
        # CircleCI に登録した環境変数を使って SSH
      - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /var/www/rails/rakudiet/ && git pull'


workflows:
  version: 2.1
        # build_and_deploy ジョブ: 一番最初に呼ばれるジョブ
    build_and_deploy:
        # build ジョブと deploy ジョブを呼び出す
      jobs:
         - build
        - deploy:
            requires:
              # deploy ジョブより先に build ジョブを実行しろ！
              - build
            # master ブランチに push された場合のみ deploy ジョブを実行する
            filters:
              branches:
                only: master
