version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  deploy:
      machine:
          image: circleci/classic:edge
      steps:
          - add_ssh_keys: 
              fingerprints:
                - 5d:f8:24:ee:43:b0:2a:12:62:63:cf:b6:1b:31:0b:e0
          - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST 'cd ~/rakudiet && git pull origin master'

workflows:
   version: 2.1
   deploy:
       jobs:
           - deploy:
               filters:
                   branches:
                       only: master
